### ISSUE TITLE
Can not install the graph app from "https://install.graphapp.io/"

### ISSUE THREAD

**Issue by lixuanxian** [neo4j-apps/neo4j-desktop#114]
1. Goto https://install.graphapp.io/

2. Click "Install" button
 
![1632755968(1)](https://user-images.githubusercontent.com/2293168/134937264-ee1670f7-942b-4c13-a394-8ba32939fb43.png)

3. You will can see the error

![1632756098(1)](https://user-images.githubusercontent.com/2293168/134937649-90fdb36b-95c0-4233-9488-0d0af06f854c.png)

3.1  The error logs

```
[2021-09-27 23:21:21.690] [info]  Starting Neo4j Desktop 1.4.8 @ Windows_NT 10.0.19043
[2021-09-27 23:21:21.767] [error] Protocol Manager error TypeError [ERR_INVALID_URL]: Invalid URL: --allow-file-access-from-files
    at onParseError (internal/url.js:256:9)
    at new URL (internal/url.js:332:5)
    at Object.t.default (D:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:197310)
    at App.<anonymous> (D:\Program Files\Neo4j Desktop\resources\app.asar\dist\main.prod.js:1:228006)
    at App.emit (events.js:315:20)
    at App.EventEmitter.emit (domain.js:483:12)
    at App.emitter.emit (D:\Program Files\Neo4j Desktop\resources\app.asar\node_modules\@sentry\electron\dist\main\integrations\electron.js:63:25)
```

**Comment by schoenmh** [comment]
I have this issue as well

**Comment by schoenmh** [comment]
It also occurs when I use a manual URL
