### ISSUE TITLE
Neo4j desktop installed but not starting

### ISSUE THREAD

**Issue by wirsel** [neo4j-apps/neo4j-desktop#134]
Dear Neo4j support
I have downloaded to day the newest Neo4j Desktop 1.5.9 version and installed it. After that I tried to launch it. Unfortunatley the program does not start. It seems to crash before and UI is shown with no message. But I found entries in the log file

[2024-06-01 11:45:06.342] [info]  â— â— â— Starting Neo4j Desktop 1.5.9 @ Windows_NT 10.0.19045, 12th Gen Intel(R) Core(TM) i7-1265U}
[2024-06-01 11:45:06.657] [info]  Initializing persistence
[2024-06-01 11:45:06.785] [info]  â— â— â— GraphQL server is running @ http://127.0.0.1:11001
[2024-06-01 11:45:06.883] [info]  Configuring crash reporting
[2024-06-01 11:45:06.885] [info]  Reading settings
[2024-06-01 11:45:06.886] [info]  PowerShell compatibility check
[2024-06-01 11:45:08.239] [info]  PowerShell version: 5. Required version: 5.
[2024-06-01 11:45:09.055] [info]  PowerShell language mode: FullLanguage
[2024-06-01 11:45:09.057] [info]  Reading bundled resources C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources
[2024-06-01 11:45:09.060] [info]  Distribution folder for java should exist
[2024-06-01 11:45:09.062] [info]  Will copy [
  'zulu11.66.19-ca-jdk11.0.20.1-win_x64.zip',
  'zulu17.44.53-ca-jdk17.0.8.1-win_x64.zip'
]
[2024-06-01 11:45:20.875] [info]  Distribution folder for neo4j should exist
[2024-06-01 11:45:25.042] [info]  Will copy []
[2024-06-01 11:45:25.045] [info]  Reading bundled resources C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources
[2024-06-01 11:45:25.082] [info]  Distribution folder for graphApps should exist
[2024-06-01 11:45:25.091] [info]  Will copy [ 'neo4j-bloom-2.10.0.tar.gz', 'neo4j-browser-5.12.0.tar.gz' ]
[2024-06-01 11:45:26.596] [info]  Copying C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\offline\plugins to C:\Users\mwis\AppData\Local\Neo4j\Relate\Cache\plugin
[2024-06-01 11:45:26.599] [info]  Copying C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\offline\plugin-versions to C:\Users\mwis\.Neo4jDesktop\relate-data\plugin-versions
[2024-06-01 11:45:26.646] [error] App initialization error Error: DbmsManifestModel validation failure:

- Property "id" failed the following constraints: id must be a UUID
    at DbmsManifestModel.validate (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\model.abstract.js:17:19)
    at new ModelAbstract (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\model.abstract.js:12:14)
    at new ManifestModel (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\manifest.model.js:18:9)
    at new DbmsManifestModel (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\dbms.model.js:26:9)
    at ManifestLocal.<anonymous> (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\entities\manifest\manifest.local.js:105:24)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\entities\manifest\manifest.local.js:5:58)
[2024-06-01 11:45:36.116] [info]  â— â— â— Starting Neo4j Desktop 1.5.9 @ Windows_NT 10.0.19045, 12th Gen Intel(R) Core(TM) i7-1265U}
[2024-06-01 11:45:36.183] [error] Protocol Manager type error: url must be string. url = undefined
[2024-06-01 11:46:45.945] [info]  â— â— â— Starting Neo4j Desktop 1.5.9 @ Windows_NT 10.0.19045, 12th Gen Intel(R) Core(TM) i7-1265U}
[2024-06-01 11:46:46.111] [info]  Initializing persistence
[2024-06-01 11:46:46.175] [info]  â— â— â— GraphQL server is running @ http://127.0.0.1:11001
[2024-06-01 11:46:46.286] [info]  Configuring crash reporting
[2024-06-01 11:46:46.288] [info]  Reading settings
[2024-06-01 11:46:46.289] [info]  PowerShell compatibility check
[2024-06-01 11:46:47.402] [info]  PowerShell version: 5. Required version: 5.
[2024-06-01 11:46:47.993] [info]  PowerShell language mode: FullLanguage
[2024-06-01 11:46:47.994] [info]  Reading bundled resources C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources
[2024-06-01 11:46:47.996] [info]  Distribution folder for java should exist
[2024-06-01 11:46:49.326] [info]  Will copy []
[2024-06-01 11:46:49.358] [info]  Distribution folder for neo4j should exist
[2024-06-01 11:46:51.823] [info]  Will copy []
[2024-06-01 11:46:51.824] [info]  Reading bundled resources C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources
[2024-06-01 11:46:51.856] [info]  Distribution folder for graphApps should exist
[2024-06-01 11:46:51.861] [warn]  Failed to read installed 'neo4j-bloom', will replace with bundled distribution Error: Graph-App[neo4j-bloom] does not contain package.json
    at getLocalMetadata (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:3897:15)
    at async newerGraphAppVersion (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:3263:22)
    at async C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5251:36
    at async Promise.all (index 0)
    at async loadResource (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5246:32)
    at async C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5312:21
    at async __webpack_modules__.9680.exports.default (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5327:5)
    at async App.<anonymous> (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:13083:9)
[2024-06-01 11:46:51.863] [warn]  Failed to read installed 'neo4j-browser', will replace with bundled distribution Error: Graph-App[neo4j-browser] does not contain package.json
    at getLocalMetadata (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:3897:15)
    at async newerGraphAppVersion (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:3263:22)
    at async C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5251:36
    at async Promise.all (index 1)
    at async loadResource (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5246:32)
    at async C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5312:21
    at async __webpack_modules__.9680.exports.default (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:5327:5)
    at async App.<anonymous> (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\dist\main.prod.js:13083:9)
[2024-06-01 11:46:51.864] [info]  Will copy [ 'neo4j-bloom-2.10.0.tar.gz', 'neo4j-browser-5.12.0.tar.gz' ]
[2024-06-01 11:46:51.968] [info]  Copying C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\offline\plugins to C:\Users\mwis\AppData\Local\Neo4j\Relate\Cache\plugin
[2024-06-01 11:46:51.971] [info]  Copying C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\offline\plugin-versions to C:\Users\mwis\.Neo4jDesktop\relate-data\plugin-versions
[2024-06-01 11:46:52.126] [error] App initialization error Error: DbmsManifestModel validation failure:

- Property "id" failed the following constraints: id must be a UUID
    at DbmsManifestModel.validate (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\model.abstract.js:17:19)
    at new ModelAbstract (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\model.abstract.js:12:14)
    at new ManifestModel (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\manifest.model.js:18:9)
    at new DbmsManifestModel (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\models\dbms.model.js:26:9)
    at ManifestLocal.<anonymous> (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\entities\manifest\manifest.local.js:105:24)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\mwis\AppData\Local\Programs\Neo4j Desktop\resources\app.asar\node_modules\@relate\common\dist\entities\manifest\manifest.local.js:5:58)
[2024-06-01 11:47:29.151] [info]  â— â— â— Starting Neo4j Desktop 1.5.9 @ Windows_NT 10.0.19045, 12th Gen Intel(R) Core(TM) i7-1265U}
[2024-06-01 11:47:29.209] [error] Protocol Manager type error: url must be string. url = undefined
[2024-06-01 11:50:07.135] [info]  â— â— â— Starting Neo4j Desktop 1.5.9 @ Windows_NT 10.0.19045, 12th Gen Intel(R) Core(TM) i7-1265U}
[2024-06-01 11:50:07.181] [error] Protocol Manager type error: url must be string. url = undefined
[2024-06-01 12:02:16.157] [info]  â— â— â— Starting Neo4j Desktop 1.5.9 @ Windows_NT 10.0.19045, 12th Gen Intel(R) Core(TM) i7-1265U}
[2024-06-01 12:02:16.231] [error] Protocol Manager type error: url must be string. url = undefined
Any idea what went wrong and how to fix this?
Best
Markus

**Comment by lyydd** [comment]
Have you solve this problem? I also find the problem in the log file
