### ISSUE TITLE
App initialization error: Error: Unknown or unsupported transport 'disabled' for address 'disabled:'

### ISSUE THREAD

**Issue by nossila** [neo4j-apps/neo4j-desktop#23]
I'm not able to start the AppImage on Ubuntu Server 16.04.3 running window manager i3. This is all the log file gives me when I try to run the `neo4j-desktop-offline-1.1.8-x86_64.AppImage`:

`[15:42:21:0885] [info] App starting
[15:42:22:0062] [info] Create PouchDB database if not exists - projects
[15:42:22:0062] [info] Create PouchDB database if not exists - databases
[15:42:22:0063] [info] Create PouchDB database if not exists - userData
[15:42:22:0063] [info] Create PouchDB database if not exists - graphApps
[15:42:22:0063] [info] Create PouchDB database if not exists - plugins
[15:42:22:0063] [info] Create PouchDB database if not exists - distributions
[15:42:22:0064] [info] Create PouchDB database if not exists - licenses
[15:42:22:0124] [info] Reading bundled resources /tmp/.mount_neo4j-bVfjO2/app/resources
[15:42:22:0128] [error] Failed to move offline resource Error: EEXIST: file already exists, link '/tmp/.mount_neo4j-bVfjO2/app/resources/offline/java' -> '/home/alisson/.config/Neo4j Desktop/Application/distributions/java'

[15:42:22:0128] [error] Failed to move offline resource Error: EEXIST: file already exists, link '/tmp/.mount_neo4j-bVfjO2/app/resources/offline/neo4j' -> '/home/alisson/.config/Neo4j Desktop/Application/distributions/neo4j'

[15:42:22:0129] [error] Failed to move offline resource Error: EEXIST: file already exists, link '/tmp/.mount_neo4j-bVfjO2/app/resources/offline/graphApps' -> '/home/alisson/.config/Neo4j Desktop/Application/graphApps'

[15:42:22:0825] [debug] No proxy type provided
[15:42:22:0826] [error] App initialization error: Error: Unknown or unsupported transport 'disabled' for address 'disabled:'`

**Comment by Metaur** [comment]
This error seems to be a bug with Chrome and its extensions on Ubuntu. 
Please refer to this bug report and suggested solution: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884173

**Comment by youngsheep7** [comment]
hi, how is this issue going? 
if it was solved, how did you do? i have came cross the same problem with ubuntu 14.04 Desktop.

**Comment by Metaur** [comment]
@youngsheep7  unfortunately, we couldn't reproduce this issue. 
What Neo4j Desktop version are you using? does the log file contain any information on the issue?

**Comment by Metaur** [comment]
@nossila @youngsheep7  Is this still an issue?

**Comment by plweller3** [comment]
This can happen when you try to run the AppImage from a terminal window (e.g. command line) as root versus, for example, launching it from a folder window as the login user.

**Comment by pebbe** [comment]
I have a similar problem.

Platform:

```
p209327@haytabo:~$ uname -a
Linux haytabo 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

p209327@haytabo:~$ java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
Running neo4j-desktop for the first time:

```
p209327@haytabo:~$ neo4j-desktop-offline-1.2.1-x86_64.AppImage 
[09:08:59.0488] [info] Starting Neo4j Desktop 1.2.1 @ Linux 4.15.0-38-generic
[09:09:00.0803] [info] GraphQL server is running @ localhost:11001
[09:09:00.0804] [info] Initializing persistence
[09:09:00.0810] [info] Creating persistent store - projects
[09:09:00.0825] [info] Creating persistent store - databases
[09:09:00.0837] [info] Creating persistent store - userData
[09:09:00.0849] [info] Creating persistent store - graphApps
[09:09:00.0862] [info] Creating persistent store - plugins
[09:09:00.0874] [info] Creating persistent store - distributions
[09:09:00.0897] [info] Creating persistent store - licenses
[09:09:00.0908] [info] Creating persistent store - karhu
[09:09:00.0924] [info] Creating persistent store - permissions
[09:09:00.0936] [info] Creating persistent store - certificates
[09:09:00.0955] [info] Configuring crash reporting
[09:09:00.0956] [info] Creating new client ID
[09:09:00.0962] [info] Reading settings
[09:09:00.0970] [info] Reading bundled resources /tmp/.mount_neo4j-HIjgrA/resources
[09:09:00.0975] [info] Distribution folder for java should exist
[09:09:00.0981] [info] Will copy [ 'zulu8.21.0.1-jdk8.0.131-linux_x64.tar.gz' ]
[09:09:01.0797] [info] Distribution folder for neo4j should exist
[09:09:01.0803] [info] Will copy [ 'neo4j-enterprise-3.5.6-unix.tar.gz' ]
[09:09:03.0659] [info] Distribution folder for graphApps should exist
[09:09:03.0666] [info] Will copy [ 'neo4j-bloom-1.1.0.tar.gz', 'neo4j-browser-3.2.20.tar.gz' ]
[09:09:03.0801] [info] Configuring proxy: NO_PROXY
[09:09:03.0827] [error] App initialization error: Error: Unknown or unsupported transport 'disabled' for address 'disabled:' Error: Unknown or unsupported transport 'disabled' for address 'disabled:'

^C[09:09:15.0376] [info] App is quitting
[09:09:15.0388] [info] App quit with 0 code
```

Running neo4j-desktop for the second time:

```
p209327@haytabo:~$ neo4j-desktop-offline-1.2.1-x86_64.AppImage 
[09:09:45.0091] [info] Starting Neo4j Desktop 1.2.1 @ Linux 4.15.0-38-generic
[09:09:46.0339] [info] GraphQL server is running @ localhost:11001
[09:09:46.0340] [info] Initializing persistence
[09:09:46.0435] [info] Configuring crash reporting
[09:09:46.0437] [info] Reading settings
[09:09:46.0437] [info] Reading bundled resources /tmp/.mount_neo4j-3ImoPb/resources
[09:09:46.0447] [info] Distribution folder for java should exist
[09:09:47.0985] [info] Will copy []
[09:09:47.0999] [info] Distribution folder for neo4j should exist
[09:09:51.0429] [info] Will copy []
[09:09:51.0445] [info] Distribution folder for graphApps should exist
[09:09:51.0480] [warn] Failed to read installed 'neo4j-bloom', will replace with bundled distribution Error: Graph-App[neo4j-bloom] does not contain package.json
    at p (/tmp/.mount_neo4j-3ImoPb/resources/app.asar/dist/main.prod.js:1:40901)

[09:09:51.0482] [warn] Failed to read installed 'neo4j-browser', will replace with bundled distribution Error: Graph-App[neo4j-browser] does not contain package.json
    at p (/tmp/.mount_neo4j-3ImoPb/resources/app.asar/dist/main.prod.js:1:40901)

[09:09:51.0482] [info] Will copy [ 'neo4j-bloom-1.1.0.tar.gz', 'neo4j-browser-3.2.20.tar.gz' ]
[09:09:51.0617] [info] Configuring proxy: NO_PROXY
[09:09:51.0648] [error] App initialization error: Error: Unknown or unsupported transport 'disabled' for address 'disabled:' Error: Unknown or unsupported transport 'disabled' for address 'disabled:'

^C[09:10:00.0049] [info] App is quitting
[09:10:00.0065] [info] App quit with 0 code
```

**Comment by pebbe** [comment]
I don't know what this does. But running these commands before starting neo4j-desktop solves this problem:

```sh
export NO_AT_BRIDGE=1
eval $(dbus-launch --sh-syntax)
export DBUS_SESSION_BUS_PID
export DBUS_SESSION_BUS_WINDOWID
eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login)
eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
```

Now everything seems to work OK, as long as I don't use the top menu bar, because when I do, the program does a segmentation fault.
