### ISSUE TITLE
`ERROR Unexpected error detected in bolt session`

### ISSUE THREAD

**Issue by whatSocks** [neo4j-apps/neo4j-desktop#25]
Graph crashing with unexpected error? 

* Download Neo4j Desktop
* Go to My Project
* Create new graph 
* Enter password and start
* After a few minutes error below happens 

```
2018-07-31 17:18:24.441+0000 INFO  ======== Neo4j 3.4.4 ========
2018-07-31 17:18:24.469+0000 INFO  Starting...
2018-07-31 17:18:35.350+0000 INFO  Initiating metrics...
2018-07-31 17:18:35.964+0000 INFO  Sending metrics to CSV file at /Users/cristinae/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-87747c3d-92b4-4133-af5b-eb8515a25c1b/installation-3.4.4/metrics
2018-07-31 17:18:38.979+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2018-07-31 17:18:38.979+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2018-07-31 17:18:46.179+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-07-31 17:18:47.816+0000 INFO  Started.
2018-07-31 17:18:47.947+0000 INFO  Mounted REST API at: /db/manage
2018-07-31 17:18:48.015+0000 INFO  Server thread metrics has been registered successfully
2018-07-31 17:18:48.532+0000 WARN  Low configured threads: (max={} - required={})={} < warnAt={} for {}
2018-07-31 17:18:48.542+0000 INFO  Remote interface available at http://localhost:7474/
2018-07-31 17:19:48.572+0000 ERROR Unexpected error detected in bolt session 'f45c89fffeba22e1-00001663-00000005-9b6db84d5ff0dd47-607b9a44'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:69)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:87)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
	at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
	at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
	... 12 more
```

**Comment by whatSocks** [comment]
I just pressed start and waited. 
I am running macOS Sierra v 10.12.6

**Comment by whatSocks** [comment]
I was also running https://github.com/neo4j-apps/graph-examples

**Comment by whatSocks** [comment]
This problem seems to have resolved by itself
