### ISSUE TITLE
Neo4j Desktop 1.1.18 won't turn off Offline Mode even though I'm connected to the internet

### ISSUE THREAD

**Issue by dnet5** [neo4j-apps/neo4j-desktop#58]
Hi,
I'm having issues with Desktop 1.1.18 on macOS Mojave 10.14.4. The app **doesn't recognize my internet connection** (theoretically), stating that either:
1. I have a poor network connection
2. I'm on a proxied network environment

![image](https://user-images.githubusercontent.com/3988029/55243492-1ec16c80-521e-11e9-984c-ebbf8569262b.png)

So, I can't turn off Offline Mode and I _have_ to click on Work Offline.

However, both of the statements aren't true.

**First**: [My connection is ok](http://www.speedtest.net/my-result/d/96985872)
![image](https://user-images.githubusercontent.com/3988029/55243840-c343ae80-521e-11e9-9958-ae75e50c8951.png)

**Second:** There aren't any proxies configured
<img width="672" alt="Screen Shot 2019-03-29 at 12 34 11" src="https://user-images.githubusercontent.com/3988029/55245544-1e2ad500-5222-11e9-8308-ed91342533eb.png">

I said that I'm _theoretically_ offline because, although it says I'm offline, I can connect to both local and remote desktops (screenshots above).

**LOCAL** (sensitive information scratched on purpose)
<img width="904" alt="Screen Shot 2019-03-29 at 12 53 48" src="https://user-images.githubusercontent.com/3988029/55245496-081d1480-5222-11e9-913f-5c5986d7e772.png">

**REMOTE** (sensitive information scratched on purpose)
<img width="1081" alt="Screen Shot 2019-03-29 at 12 48 04" src="https://user-images.githubusercontent.com/3988029/55245178-64cbff80-5221-11e9-8ba9-2b1e90540e2a.png">

Some other information:

- This error appeared on 1.1.18; until 1.1.17 everything was fine
- I can perform any actions on the database (writing and reading queries, load Bloom, Browser, run analytics through third graph apps; everything)
- I've tried in another network (same thing, 5Ghz wifi without proxies or VPN), and the error persists

Still, can't exit Offline Mode 😞

For any further informartion needed, I'll be glad to help.

**Comment by oskarhane** [comment]
Hi and thanks for the report @dnet5!
This sounds unusual.

What if you go to settings, is the "Enable offline mode" config selected?
If it is, try to disable it.

It does sound like a bug that you can connect to remote graphs even though you're offline. It should be fine if you're connecting to a LAN (or even local) address, but WAN addresses should not be available to connect to.
It's almost like you're in a state in partial offline mode.

Do you have a firewall or filter that stops requests to certain addresses?
You can see a list of URL:s we use to check online status here: https://github.com/neo4j-apps/neo4j-desktop/wiki/FAQ#what-public-internet-addresses-does-neo4j-desktop-reach-out-to-and-for-what-reason

**Comment by dnet5** [comment]
> _What if you go to settings, is the "Enable offline mode" config selected? If it is, try to disable it._

Yes. Offiline Mode is ticked and can't be uncheck. Once I try to do it, the first image I've posted pops up and states that I have no connection, asking either to configure a proxy or to work offline (option that I hit).

> It does sound like a bug that you can connect to remote graphs even though you're offline. It should be fine if you're connecting to a LAN (or even local) address, but WAN addresses should not be available to connect to. It's almost like you're in a state in partial offline mode.

I'm on WAN, nothing running on LAN mode. That's why it is so weird.

> Do you have a firewall or filter that stops requests to certain addresses?

Nope. Not at all.

**Comment by oskarhane** [comment]
@dnet5 Thanks for the response. 
Could you send me your desktop log file (you get to it by pressing ctrl+k and type "log" and select the desktop log file option)?
You can send it to oskar.hane at neo4j dot com.

**Comment by dnet5** [comment]
Sure. I'll send it right away!

**Comment by oskarhane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Neo4j Desktop 1.1.18 won't turn off Offline Mode even though I'm connected to the internet](https://trello.com/c/XjYner2U/916-neo4j-desktop-1118-wont-turn-off-offline-mode-even-though-im-connected-to-the-internet)

**Comment by oskarhane** [comment]
@dnet5 Thanks, we'll have a look and get back to you soon.

**Comment by Metaur** [comment]
@dnet5 Could you please open the URL, that Desktop uses for checking the online connectivity (`https://captive.apple.com/hotspot-detect.html`)? Please check the response body and status code.

Also, open chrome with a link `chrome://net-internals/#proxy` to just be sure there is nothing around proxies.

**Comment by dnet5** [comment]
Hey, Sergey!

Here are the prints for checking.

*Apple Captive*
[image: image.png]
*Chrome proxies*
[image: image.png]

Best,


DEOCLIDES Neto
about.me/deoclides  [image: LinkedIn]
<http://www.linkedin.com/profile/view?id=62839394>
  +55 11 972 459 011
[image: DEOCLIDES Neto on about.me]


Em qua, 3 de abr de 2019 às 06:30, Sergey Kolunov <notifications@github.com>
escreveu:

**Comment by Metaur** [comment]
@dnet5 could you please attach the images. Seems like those did not get uploaded

**Comment by dnet5** [comment]
Sure!


DEOCLIDES Neto
about.me/deoclides  [image: LinkedIn]
<http://www.linkedin.com/profile/view?id=62839394>
  +55 11 972 459 011
[image: DEOCLIDES Neto on about.me]


Em qui, 4 de abr de 2019 às 06:01, Sergey Kolunov <notifications@github.com>
escreveu:

**Comment by wilsli** [comment]
same problem with the version 1.1.22.
Checked the log file, just a bunch of "max tries exceeded" error there: 

>[2019-05-20 23:52:59:0561] [info] Function[]
[2019-05-20 23:53:00:0529] [info] Action[APPLICATION_SETTINGS_SAVED] { settings: { defaultProtocolRemember: false },
  type: 'APPLICATION_SETTINGS_SAVED' }
[2019-05-20 23:53:00:0842] [info] Function[]
[2019-05-20 23:53:02:0522] [info] Function[]
[2019-05-20 23:53:02:0535] [info] Action[APPLICATION_SETTINGS_SAVED] { settings: { defaultProtocolRemember: true },
  type: 'APPLICATION_SETTINGS_SAVED' }
[2019-05-20 23:53:03:0491] [info] Function[]
[2019-05-20 23:53:03:0507] [info] Action[APPLICATION_SETTINGS_SAVED] { settings: { defaultProtocol: true },
  type: 'APPLICATION_SETTINGS_SAVED' }
[2019-05-20 23:53:05:0174] [info] Action[NEO4J_RELEASE_NOTES_LOADED]
[2019-05-20 23:53:05:0488] [info] Action[SIDEBAR_OPEN_TAB] { sidebarTab: 'settings', type: 'SIDEBAR_OPEN_TAB' }
[2019-05-20 23:53:05:0490] [info] Action[APPLICATION_SETTINGS_CLOSE_TELEMETRY_DIALOG] { type: 'APPLICATION_SETTINGS_CLOSE_TELEMETRY_DIALOG' }
[2019-05-20 23:53:10:0886] [info] Function[]
[2019-05-20 23:53:10:0899] [info] Action[APPLICATION_SETTINGS_SAVED] { settings: { enableOfflineMode: false },
  type: 'APPLICATION_SETTINGS_SAVED' }
[2019-05-20 23:53:17:0318] [info] Checking online status...
[2019-05-20 23:53:34:0290] [error] Error: Max tries exceeded
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:39927)
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:40001)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-20 23:53:34:0295] [info] Online status: Application is offline
[2019-05-20 23:53:40:0315] [error] Error: Max tries exceeded
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:39927)
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:40001)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-20 23:54:01:0374] [error] Error: Max tries exceeded
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:39927)
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:40001)
[2019-05-20 23:54:20:0456] [error] Error: Max tries exceeded
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:39927)
    at run (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/dist/main.prod.js:1:40001)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I can't even install Graph Algorithm plugin or so.

**Comment by maheshhatolkar** [comment]
I'm also facing the same issue with Neo4j Desktop 1.1.22.

**Comment by maheshhatolkar** [comment]
2019-05-22 15:47:44.187+0000 INFO  ======== Neo4j 3.5.2 ========
2019-05-22 15:47:44.196+0000 INFO  Starting...
2019-05-22 15:47:45.545+0000 INFO  Initiating metrics...
2019-05-22 15:47:48.479+0000 INFO  Sending metrics to CSV file at C:\Users\mahesh\.Neo4jDesktop\neo4jDatabases\database-2ab99906-b4e4-49f9-b377-1bd1da4cc0e4\installation-3.5.2\metrics
2019-05-22 15:47:49.368+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2019-05-22 15:47:51.511+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2019-05-22 15:47:51.511+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2019-05-22 15:47:52.149+0000 INFO  Started.
2019-05-22 15:47:52.523+0000 INFO  Mounted REST API at: /db/manage
2019-05-22 15:47:52.698+0000 INFO  Server thread metrics have been registered successfully
2019-05-22 15:47:53.776+0000 INFO  Remote interface available at http://localhost:7474/

**Comment by Metaur** [comment]
@wilsli Could you please install a latest Desktop Canary build and check the online connectivity there? If that fails - please share your logs, they will help in further investigation

**Comment by Metaur** [comment]
@maheshhatolkar You have provided the Neo4j logs, not Neo4j Desktop. While in Desktop, press Ctrl+K (on win and linux) or Cmd+K (on mac), type log to find the Desktop log file.

**Comment by willsgh** [comment]
I'm having the same problem

**Comment by tanghw** [comment]
same with me,but 1.11.7 is ok,1.1.22 is not ok

**Comment by PinkusKSquare** [comment]
Any update on this? I'm having the same issue with v 1.1.18 on ubuntu 16.04 LTS

**Comment by dnet5** [comment]
> Any update on this? I'm having the same issue with v 1.1.18 on ubuntu 16.04 LTS

The problem was gone after upgrading from 1.1.18. Now I'm on 1.2.1 and I don't have this bug anymore, nor on Mac or Windows. Didn't tested on Ubuntu, though. But I think is a bug from 1.1.18. Try updating.

**Comment by apoorvkapil** [comment]
I experienced same issue even on 1.2.3. However when i unchecked the Enable Offline Mode, the same below pop-up appeared. 

https://user-images.githubusercontent.com/3988029/55243492-1ec16c80-521e-11e9-984c-ebbf8569262b.png

I clicked on "Check Online Status" and it went fine.

**Comment by hadirsa** [comment]
I have the same issue with v1.2.4.
OS: Ubuntu 18.04

**Comment by madiskou** [comment]
same issue with 1.2.4
Windows 10

**Comment by 7Fathoms** [comment]
Same here with 1.24 and Win 10.

**Comment by alexaurea** [comment]
Same here, 1.2.4 and Win 10

**Comment by madiskou** [comment]
> 
> 
> same issue with 1.2.4
> Windows 10

Works for with a proxy configuration
