### ISSUE TITLE
Database is not restarting.

### ISSUE THREAD

**Issue by AmiPandat** [neo4j-apps/neo4j-desktop#62]
I am facing this issue since two days . If I create a dtabase and after somtime if I start it agaian it shows the error  **" Database failed to start: DB [database-3632311f-bd8b-4308-a7c5-8c19e60c37d7] 'v3.4.1' exited with status 'KILLED'. Check the logs
"**

Logs

2019-04-11 12:54:14.354+0000 INFO  ======== Neo4j 3.4.7 ========
2019-04-11 12:54:14.408+0000 INFO  Starting...
2019-04-11 12:54:17.229+0000 INFO  Initiating metrics...
2019-04-11 12:54:20.398+0000 INFO  Sending metrics to CSV file at C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\metrics
2019-04-11 12:54:20.976+0000 INFO  Bolt enabled on 127.0.0.1:11014.
2019-04-11 12:54:23.497+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2019-04-11 12:54:23.608+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2019-04-11 12:54:24.636+0000 INFO  Started.
2019-04-11 12:54:24.906+0000 INFO  Mounted REST API at: /db/manage
2019-04-11 12:54:25.011+0000 INFO  Server thread metrics has been registered successfully
2019-04-11 12:54:26.254+0000 INFO  Remote interface available at http://localhost:11015/
2019-04-11 12:55:18.062+0000 WARN  The client is unauthorized due to authentication failure.
2019-04-11 15:42:49.417+0000 WARN  The client is unauthorized due to authentication failure.
2019-04-11 17:26:15.287+0000 INFO  ======== Neo4j 3.4.7 ========
2019-04-11 17:26:15.552+0000 INFO  Starting...
2019-04-11 17:26:18.587+0000 INFO  Initiating metrics...
2019-04-11 17:26:18.903+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6b54655f' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6b54655f' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6b54655f' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6b54655f' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:39)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:78)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@7fc44dec' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Store and its lock file has been locked by another process: C:\Users\daiict\.Neo4jDesktop\neo4jDatabases\database-3632311f-bd8b-4308-a7c5-8c19e60c37d7\installation-3.4.1\data\databases\graph.db\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:117)
	at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:93)
	at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:60)
	at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2019-04-11 17:26:18.904+0000 INFO  Neo4j Server shutdown initiated by request

Can you please help me with this?

**Comment by Metaur** [comment]
@AmiPandat seems like you've got a neo4j process stuck in memory. Please check a process manager for any running Zulu processes and kill those. 
Normally Desktop should do that for you when it starts. Which version of Desktop are you using? OS? Could you share the logs and steps to reproduce the issue?

**Comment by AmiPandat** [comment]
> 
> 
> @AmiPandat seems like you've got a neo4j process stuck in memory. Please check a process manager for any running Zulu processes and kill those.
> Normally Desktop should do that for you when it starts. Which version of Desktop are you using? OS? Could you share the logs and steps to reproduce the issue?

**Comment by AmiPandat** [comment]
![image](https://user-images.githubusercontent.com/49384568/56015258-08cfa380-5d16-11e9-8bb9-3bf9fe80e724.png)

Neo4j Desktop Version : 1.1.17
Windows 7
[neo4j.log](https://github.com/neo4j-apps/neo4j-desktop/files/3071777/neo4j.log)

I have attached logs.
Thanking You!
